name: CI/CD for Spring Boot

on:
  push:
    branches:
      - feature/korail/hanseop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 54.180.119.254 >> ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KORAIL_SSH_KEY_HANSEOP }}

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Check for built JAR file
        run: |
          echo "Searching for korail-0.0.1-SNAPSHOT.jar..."
          find . -name "korail-0.0.1-SNAPSHOT.jar"

      - name: Check if JAR file exists
        run: |
          echo "Checking for korail-0.1-SNAPSHOT.jar in build/libs"
          ls -la build/libs

      - name: Give read permission to JAR file
        run: |
          chmod +r build/libs/korail-0.0.1-SNAPSHOT.jar

      - name: Give read and execute permissions to build/libs directory
        run: |
          chmod +rx build/libs

      - name: Copy JAR file to Remote Server via SCP
        uses: appleboy/scp-action@v0.1.1
        with:
          host: "54.180.119.254"
          username: "ubuntu"
          port: 22
          key: ${{ secrets.KORAIL_SSH_KEY_HANSEOP }}
          source: "./build/libs/korail-0.0.1-SNAPSHOT.jar"
          target: "/home/ubuntu/korail/build/libs/"

      - name: Restart Docker Container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: "54.180.119.254"
          username: "ubuntu"
          key: ${{ secrets.KORAIL_SSH_KEY_HANSEOP }}
          script: |
            cd /home/ubuntu/korail
            docker-compose down
            docker-compose up -d --build
